
USE ETL;
DROP EVENT IF EXISTS DarwinETLMasterEvent;

CREATE EVENT DarwinETLMasterEvent
  ON SCHEDULE
    EVERY 1 DAY
    STARTS TIMESTAMP '2025-03-01 23:59:00'
  DO
	CALL `ETL`.`DarwinETLMaster`();


SHOW EVENTS FROM ETL;

